// Built by Anointed Coder.
//
// Pasha WinGo round engine: the money core. Mirrors the existing native
// games (dice / mines / crash) for every wallet movement, ledger write,
// turnover accrual and cashback scope stamping. Nothing here trusts the
// client: round state, bet acceptance, the draw and every payout are
// decided server-side.
//
// The pieces:
//   - computeRoundWindow(mode, at)  epoch-anchored deterministic window
//   - ensureRounds(mode)            idempotent upsert of current + next
//   - computeResult(seed, period)   crypto 0..9 from the committed seed
//   - placeBet(input)               guarded wallet debit + WingoBet
//   - settleRound(roundId)          guarded draw + exactly-once payout
//   - wingoTick()                   cron driver: ensure + close + settle
//
// Money safety guarantees (the whole point):
//   1. A bet at/after betCloseAt is rejected server-side, not just hidden.
//   2. The draw is generated by exactly one caller: status open|closed ->
//      drawn via a guarded updateMany so concurrent crons cannot re-roll.
//   3. Each bet is paid exactly once: the WON/LOST flip is a guarded
//      updateMany on status = PENDING, so a re-run or a concurrent tick
//      can never double-pay or double-debit.
//   4. Re-running settlement on an already-settled round is a no-op.
//   5. Winnings are credited through the same wallet + Transaction ledger
//      path (type 'win', meta.scope 'casino') the other native games use,
//      so turnover and cashback scope accrue identically.

import { Prisma } from '@prisma/client';
import type { WingoRound } from '@prisma/client';
import { createHmac, randomBytes } from 'node:crypto';
import { db } from '@/lib/db/client';
import { encryptString, decryptString } from '@/lib/crypto/aead';
import { generateServerSeed, hashServerSeed } from '@/lib/native-games/provably-fair';
import {
  WINGO_MODES,
  WINGO_MODE_LIST,
  WINGO_GAME_CODE,
  WINGO_EPOCH_MS,
  WINGO_DAY_MS,
  WINGO_TZ_OFFSET_MS,
  WINGO_BET_CLOSE_LEAD_MS,
  WINGO_MIN_STAKE,
  WINGO_MAX_STAKE,
  WINGO_MIN_QUANTITY,
  WINGO_MAX_QUANTITY,
  isWingoMode,
  type WingoMode,
} from './config';
import {
  payoutMultiplier,
  resultColorIdentity,
  resultSize,
  isValidSelection,
} from './paytable';

// ---------- Errors surfaced to the route layer ----------

export const WINGO_ERRORS = {
  INVALID_MODE: 'WINGO_INVALID_MODE',
  INVALID_BET_TYPE: 'WINGO_INVALID_BET_TYPE',
  INVALID_SELECTION: 'WINGO_INVALID_SELECTION',
  INVALID_QUANTITY: 'WINGO_INVALID_QUANTITY',
  STAKE_BELOW_MIN: 'WINGO_STAKE_BELOW_MIN',
  STAKE_ABOVE_MAX: 'WINGO_STAKE_ABOVE_MAX',
  ROUND_NOT_FOUND: 'WINGO_ROUND_NOT_FOUND',
  ROUND_NOT_READY: 'WINGO_ROUND_NOT_READY',
  BET_CLOSED: 'WINGO_BET_CLOSED',
  WALLET_NOT_FOUND: 'WINGO_WALLET_NOT_FOUND',
  INSUFFICIENT_FUNDS: 'WINGO_INSUFFICIENT_FUNDS',
} as const;

function dec(value: number | string | Prisma.Decimal): Prisma.Decimal {
  return new Prisma.Decimal(value);
}

// ---------- Deterministic round scheduler ----------

export interface RoundWindow {
  mode: WingoMode;
  // Global round index counted from the fixed epoch. index+1 is the next
  // round of this mode; the streams are continuous and gapless.
  index: number;
  periodNumber: string;
  startsAt: Date;
  betCloseAt: Date;
  drawsAt: Date;
}

// The human-facing period id: YYYYMMDD (local BST calendar day of the
// round start) + the mode's seconds tag + a 5-digit per-mode-per-day
// running sequence. Because the epoch is pinned to a BST midnight and
// every duration divides a day evenly, index % roundsPerDay is exactly
// the 0-based position of the round within its local day.
function periodNumberFor(mode: WingoMode, index: number, startMs: number): string {
  const cfg = WINGO_MODES[mode];
  const roundsPerDay = WINGO_DAY_MS / cfg.durationMs;
  const seqInDay = (((index % roundsPerDay) + roundsPerDay) % roundsPerDay) + 1;
  const local = new Date(startMs + WINGO_TZ_OFFSET_MS);
  const y = local.getUTCFullYear();
  const m = String(local.getUTCMonth() + 1).padStart(2, '0');
  const d = String(local.getUTCDate()).padStart(2, '0');
  const seq = String(seqInDay).padStart(5, '0');
  return `${y}${m}${d}${cfg.secondsTag}${seq}`;
}

// Given a mode and an instant, compute that mode's round window that
// CONTAINS the instant. Pure and deterministic, no DB read.
export function computeRoundWindow(mode: WingoMode, at: Date | number): RoundWindow {
  const cfg = WINGO_MODES[mode];
  const nowMs = typeof at === 'number' ? at : at.getTime();
  const index = Math.floor((nowMs - WINGO_EPOCH_MS) / cfg.durationMs);
  return roundWindowByIndex(mode, index);
}

// Materialise a specific round index into a window.
export function roundWindowByIndex(mode: WingoMode, index: number): RoundWindow {
  const cfg = WINGO_MODES[mode];
  const startMs = WINGO_EPOCH_MS + index * cfg.durationMs;
  const drawMs = startMs + cfg.durationMs;
  const betCloseMs = drawMs - WINGO_BET_CLOSE_LEAD_MS;
  return {
    mode,
    index,
    periodNumber: periodNumberFor(mode, index, startMs),
    startsAt: new Date(startMs),
    betCloseAt: new Date(betCloseMs),
    drawsAt: new Date(drawMs),
  };
}

// ---------- Fairness commit + result generation ----------

// Uniform integer 0..9 derived from the committed server seed. The seed
// is 32 crypto-random bytes fixed at round open, so the digit is
// cryptographically random and cannot be steered by the operator; it is
// also deterministic from (seed, periodNumber), so once the seed is
// revealed anyone can recompute the draw and audit it. Bytes 250..255
// are rejected so the modulo 10 is perfectly uniform (0..249 tiles ten
// buckets of 25 exactly).
export function computeResult(serverSeed: string, periodNumber: string): number {
  for (let cursor = 0; cursor <= 1024; cursor += 1) {
    const block = createHmac('sha256', serverSeed)
      .update(`wingo:${periodNumber}:${cursor}`)
      .digest();
    for (let i = 0; i < block.length; i += 1) {
      const b = block[i];
      if (b < 250) return b % 10;
    }
  }
  // Astronomically unreachable; fail closed rather than emit a biased draw.
  throw new Error('WINGO_DRAW_ENTROPY_EXHAUSTED');
}

// ---------- Round provisioning (lazy + idempotent) ----------

// Ensure a single round row exists for a window. Idempotent on the
// (mode, periodNumber) unique key. The fairness seed is committed here,
// at open, and never overwritten afterwards. Safe under concurrent
// callers: a lost create race resolves to the existing row.
export async function ensureRound(window: RoundWindow): Promise<WingoRound> {
  const existing = await db.wingoRound.findUnique({
    where: { mode_periodNumber: { mode: window.mode, periodNumber: window.periodNumber } },
  });
  if (existing) return existing;

  const serverSeed = generateServerSeed();
  try {
    return await db.wingoRound.create({
      data: {
        mode: window.mode,
        periodNumber: window.periodNumber,
        status: 'open',
        startsAt: window.startsAt,
        betCloseAt: window.betCloseAt,
        drawsAt: window.drawsAt,
        serverSeed: encryptString(serverSeed),
        serverSeedHash: hashServerSeed(serverSeed),
      },
    });
  } catch (err) {
    // Lost the create race with a concurrent caller. The other write
    // committed the seed; return that row.
    if (err instanceof Prisma.PrismaClientKnownRequestError && err.code === 'P2002') {
      const row = await db.wingoRound.findUnique({
        where: { mode_periodNumber: { mode: window.mode, periodNumber: window.periodNumber } },
      });
      if (row) return row;
    }
    throw err;
  }
}

// Ensure the current and next round rows exist for a mode. Returns both.
export async function ensureRounds(mode: WingoMode, at: Date | number = Date.now()): Promise<{ current: WingoRound; next: WingoRound }> {
  const current = computeRoundWindow(mode, at);
  const next = roundWindowByIndex(mode, current.index + 1);
  const [curRow, nextRow] = await Promise.all([ensureRound(current), ensureRound(next)]);
  return { current: curRow, next: nextRow };
}

// Lazy read helper for the UI: ensure the current round exists and hand
// it back so the client is correct even between cron ticks.
export async function getCurrentRound(mode: WingoMode, at: Date | number = Date.now()): Promise<WingoRound> {
  const { current } = await ensureRounds(mode, at);
  return current;
}

// ---------- Bet placement (guarded wallet debit) ----------

export interface PlaceBetInput {
  userId: string;
  mode: WingoMode;
  betType: string;   // color | number | size
  betValue: string;  // green|red|violet | "0".."9" | big|small
  unitAmount: number | string;
  quantity: number;  // X1..X100 chip
  idempotencyKey?: string;
}

export interface PlaceBetResult {
  betId: string;
  roundId: string;
  periodNumber: string;
  mode: string;
  betType: string;
  betValue: string;
  unitAmount: number;
  quantity: number;
  betAmount: number;
  status: 'PENDING';
  newBalance: number;
  reused: boolean;
}

export async function placeBet(input: PlaceBetInput): Promise<PlaceBetResult> {
  if (!isWingoMode(input.mode)) throw new Error(WINGO_ERRORS.INVALID_MODE);
  if (input.betType !== 'color' && input.betType !== 'number' && input.betType !== 'size') {
    throw new Error(WINGO_ERRORS.INVALID_BET_TYPE);
  }
  if (!isValidSelection(input.betType, input.betValue)) throw new Error(WINGO_ERRORS.INVALID_SELECTION);

  const quantity = Number(input.quantity);
  if (!Number.isInteger(quantity) || quantity < WINGO_MIN_QUANTITY || quantity > WINGO_MAX_QUANTITY) {
    throw new Error(WINGO_ERRORS.INVALID_QUANTITY);
  }

  const unit = dec(input.unitAmount);
  if (!unit.isFinite() || unit.lt(WINGO_MIN_STAKE)) throw new Error(WINGO_ERRORS.STAKE_BELOW_MIN);
  const betAmount = unit.mul(quantity).toDecimalPlaces(2);
  if (betAmount.gt(WINGO_MAX_STAKE)) throw new Error(WINGO_ERRORS.STAKE_ABOVE_MAX);

  // Provision the round outside the transaction (idempotent). Betting is
  // always against the current window of the mode.
  const window = computeRoundWindow(input.mode, Date.now());
  const round = await ensureRound(window);

  return await db.$transaction(async (tx) => {
    const now = new Date();

    // Server-enforced bet close, by TIME not just DB status: a bet at or
    // after betCloseAt is rejected even if a tick has not yet flipped the
    // row to closed.
    if (now.getTime() >= round.betCloseAt.getTime()) throw new Error(WINGO_ERRORS.BET_CLOSED);

    const fresh = await tx.wingoRound.findUnique({ where: { id: round.id } });
    if (!fresh) throw new Error(WINGO_ERRORS.ROUND_NOT_FOUND);
    if (fresh.status !== 'open') throw new Error(WINGO_ERRORS.BET_CLOSED);

    // userId is always the prefix so one user's stored key can never collide
    // with or be read back by another, even when the client supplies the key.
    const idemSuffix = (input.idempotencyKey?.trim() || `${round.id}:${randomBytes(9).toString('hex')}`).slice(0, 100);
    const idempotencyKey = `${input.userId}:${idemSuffix}`;

    // Replay protection: a retried placement with the same key returns
    // the stored bet, wallet untouched.
    const prior = await tx.wingoBet.findUnique({ where: { idempotencyKey } });
    if (prior) {
      const w = await tx.wallet.findUnique({ where: { userId: input.userId }, select: { balance: true } });
      return {
        betId: prior.id,
        roundId: prior.roundId,
        periodNumber: fresh.periodNumber,
        mode: prior.mode,
        betType: prior.betType,
        betValue: prior.betValue,
        unitAmount: Number(prior.unitAmount),
        quantity: prior.quantity,
        betAmount: Number(prior.betAmount),
        status: 'PENDING' as const,
        newBalance: Number(w?.balance ?? 0),
        reused: true,
      };
    }

    const wallet = await tx.wallet.findUnique({ where: { userId: input.userId } });
    if (!wallet) throw new Error(WINGO_ERRORS.WALLET_NOT_FOUND);
    if (dec(wallet.balance).lt(betAmount)) throw new Error(WINGO_ERRORS.INSUFFICIENT_FUNDS);

    // 1. Debit the stake.
    await tx.wallet.update({
      where: { userId: input.userId },
      data: { balance: { decrement: betAmount } },
    });

    // 2. Create the pending bet line.
    const bet = await tx.wingoBet.create({
      data: {
        roundId: round.id,
        userId: input.userId,
        mode: input.mode,
        betType: input.betType,
        betValue: input.betValue,
        unitAmount: unit,
        quantity,
        betAmount,
        status: 'PENDING',
        idempotencyKey,
      },
    });

    // 3. Ledger: the bet debit. type 'bet' + meta.scope 'casino' is what
    //    turnover and cashback aggregate on, exactly like the other
    //    native games.
    await tx.transaction.create({
      data: {
        userId: input.userId,
        type: 'bet',
        status: 'completed',
        amount: betAmount.neg(),
        reference: round.id,
        description: 'Pasha WinGo bet',
        meta: {
          gameCode: WINGO_GAME_CODE,
          mode: input.mode,
          roundId: round.id,
          periodNumber: round.periodNumber,
          betId: bet.id,
          betType: input.betType,
          betValue: input.betValue,
          quantity,
          scope: 'casino',
        } as Prisma.JsonObject,
      },
    });

    // 4. Round audit aggregates.
    await tx.wingoRound.update({
      where: { id: round.id },
      data: { betCount: { increment: 1 }, totalStake: { increment: betAmount } },
    });

    const after = await tx.wallet.findUnique({ where: { userId: input.userId }, select: { balance: true } });
    return {
      betId: bet.id,
      roundId: round.id,
      periodNumber: round.periodNumber,
      mode: input.mode,
      betType: input.betType,
      betValue: input.betValue,
      unitAmount: Number(unit),
      quantity,
      betAmount: Number(betAmount),
      status: 'PENDING' as const,
      newBalance: Number(after?.balance ?? 0),
      reused: false,
    };
  });
}

// ---------- Settlement (guarded draw + exactly-once payout) ----------

export interface SettleResult {
  roundId: string;
  mode: string;
  periodNumber: string;
  status: string;
  result: number | null;
  resultColor: string | null;
  resultSize: string | null;
  betsSettled: number;
  betsWon: number;
  totalStake: number;
  totalPayout: number;
  // True when this call found the round already settled (no work done).
  alreadySettled: boolean;
  // True when THIS call performed the draw (won the guarded transition).
  drewThisCall: boolean;
}

async function buildSettleView(round: WingoRound, opts: { alreadySettled: boolean; drewThisCall: boolean }): Promise<SettleResult> {
  const [betsWon, betsSettled] = await Promise.all([
    db.wingoBet.count({ where: { roundId: round.id, status: 'WON' } }),
    db.wingoBet.count({ where: { roundId: round.id, status: { in: ['WON', 'LOST'] } } }),
  ]);
  return {
    roundId: round.id,
    mode: round.mode,
    periodNumber: round.periodNumber,
    status: round.status,
    result: round.result,
    resultColor: round.resultColor,
    resultSize: round.resultSize,
    betsSettled,
    betsWon,
    totalStake: Number(round.totalStake),
    totalPayout: Number(round.totalPayout),
    alreadySettled: opts.alreadySettled,
    drewThisCall: opts.drewThisCall,
  };
}

// Pay every still-PENDING bet of a drawn round in BOUNDED BATCHES. Each
// batch settles in its own short transaction and every bet is flipped by a
// guarded updateMany on status = PENDING, which is what keeps settlement
// safe on a busy round:
//   - a batch is capped at 100 bets, so it can never exceed the Prisma
//     transaction timeout and leave winners unpaid;
//   - a bet is credited exactly once (the guarded flip matches 0 rows on a
//     re-run or a concurrent tick, so its wallet credit + ledger row are
//     skipped entirely);
//   - a crash mid-round leaves already-paid bets flipped and the rest
//     still PENDING, so the next call resumes exactly where it stopped.
// It does not touch the round aggregate; finalizeRoundTotals recomputes
// those authoritatively once no PENDING bet remains.
async function drainPendingBets(
  roundId: string,
  result: number,
  periodNumber: string,
  now: Date,
): Promise<void> {
  // Progress is guaranteed: every loop flips >= 1 bet out of PENDING (or a
  // concurrent caller already did), so the PENDING set strictly shrinks.
  // The counter is pure paranoia against an unforeseen stall.
  for (let guard = 0; guard < 100_000; guard += 1) {
    const batch = await db.wingoBet.findMany({
      where: { roundId, status: 'PENDING' },
      orderBy: { createdAt: 'asc' },
      take: 100,
    });
    if (batch.length === 0) return;

    await db.$transaction(
      async (tx) => {
        for (const bet of batch) {
          const mult = payoutMultiplier(bet.betType, bet.betValue, result);
          const won = mult > 0;
          const payout = won ? dec(bet.betAmount).mul(mult).toDecimalPlaces(2) : dec(0);

          // Guarded flip: only the caller that actually moves this bet out
          // of PENDING (count === 1) credits it. A re-run or a concurrent
          // tick matches 0 rows and skips the wallet write.
          const flip = await tx.wingoBet.updateMany({
            where: { id: bet.id, status: 'PENDING' },
            data: {
              status: won ? 'WON' : 'LOST',
              payoutMultiplier: mult,
              payoutAmount: payout,
              settledAt: now,
            },
          });
          if (flip.count === 0) continue; // another caller already settled it

          if (won) {
            // Credit the win through the same ledger path the native games
            // use: wallet increment + a 'win' Transaction stamped scope
            // 'casino' so turnover and cashback accrue identically.
            await tx.wallet.update({
              where: { userId: bet.userId },
              data: { balance: { increment: payout } },
            });
            await tx.transaction.create({
              data: {
                userId: bet.userId,
                type: 'win',
                status: 'completed',
                amount: payout,
                reference: roundId,
                description: 'Pasha WinGo win',
                meta: {
                  gameCode: WINGO_GAME_CODE,
                  mode: bet.mode,
                  roundId,
                  periodNumber,
                  betId: bet.id,
                  betType: bet.betType,
                  betValue: bet.betValue,
                  result,
                  multiplier: mult,
                  scope: 'casino',
                } as Prisma.JsonObject,
              },
            });
          }
        }
      },
      { timeout: 20_000, maxWait: 5_000 },
    );
  }
}

// Recompute the round's audit aggregates from the authoritative bet rows
// and, when asked, flip drawn -> settled exactly once. SETTING the totals
// (not incrementing) makes this fully idempotent: a re-run or a concurrent
// caller writes the identical values. Called only after drainPendingBets
// has left no PENDING bet, so the sums are final.
async function finalizeRoundTotals(
  roundId: string,
  now: Date,
  opts: { settle: boolean },
): Promise<{ settledNow: boolean }> {
  return db.$transaction(async (tx) => {
    const agg = await tx.wingoBet.aggregate({
      where: { roundId },
      _count: { _all: true },
      _sum: { betAmount: true, payoutAmount: true },
    });
    await tx.wingoRound.update({
      where: { id: roundId },
      data: {
        betCount: agg._count._all,
        totalStake: agg._sum.betAmount ?? dec(0),
        totalPayout: agg._sum.payoutAmount ?? dec(0),
      },
    });
    if (!opts.settle) return { settledNow: false };
    // Guarded terminal flip: exactly one caller moves drawn -> settled.
    const upd = await tx.wingoRound.updateMany({
      where: { id: roundId, status: 'drawn' },
      data: { status: 'settled', settledAt: now },
    });
    return { settledNow: upd.count === 1 };
  });
}

export async function settleRound(roundId: string): Promise<SettleResult> {
  const round = await db.wingoRound.findUnique({ where: { id: roundId } });
  if (!round) throw new Error(WINGO_ERRORS.ROUND_NOT_FOUND);

  // Fast idempotent exit: a fully settled round does no further work.
  if (round.status === 'settled') {
    return buildSettleView(round, { alreadySettled: true, drewThisCall: false });
  }

  const now = new Date();
  if (now.getTime() < round.drawsAt.getTime()) {
    throw new Error(WINGO_ERRORS.ROUND_NOT_READY);
  }

  // ---- Phase 1: guarded draw. Exactly one caller flips the round to
  // drawn and writes the result. This stays its own short guarded
  // updateMany. The result is deterministic from the committed seed, so
  // even the callers who lose the race agree on it.
  let drewThisCall = false;
  if (round.status === 'open' || round.status === 'closed') {
    const seed = decryptString(round.serverSeed);
    const result = computeResult(seed, round.periodNumber);
    const drawUpd = await db.wingoRound.updateMany({
      where: { id: roundId, status: { in: ['open', 'closed'] } },
      data: {
        status: 'drawn',
        result,
        resultColor: resultColorIdentity(result),
        resultSize: resultSize(result),
        drawnAt: now,
      },
    });
    drewThisCall = drawUpd.count === 1;
  }

  // Reload the authoritative drawn state (ours or the race winner's).
  const drawn = await db.wingoRound.findUnique({ where: { id: roundId } });
  if (!drawn) throw new Error(WINGO_ERRORS.ROUND_NOT_FOUND);
  if (drawn.status === 'settled') {
    return buildSettleView(drawn, { alreadySettled: true, drewThisCall });
  }
  if (drawn.result === null) {
    // A concurrent caller is mid-draw. Do nothing rather than pay against
    // an unknown result; the next tick settles it.
    throw new Error(WINGO_ERRORS.ROUND_NOT_READY);
  }

  // ---- Phase 2: pay every pending bet exactly once in bounded batches,
  // then recompute the aggregates and flip drawn -> settled. Each batch is
  // its own short transaction and each bet flip is guarded, so a busy round
  // never times out and nothing is ever double-paid. Totals + the settled
  // status/timestamp are written only after no PENDING bet remains.
  await drainPendingBets(roundId, drawn.result, drawn.periodNumber, now);
  const { settledNow } = await finalizeRoundTotals(roundId, now, { settle: true });

  const final = await db.wingoRound.findUnique({ where: { id: roundId } });
  return buildSettleView(final ?? drawn, { alreadySettled: !settledNow, drewThisCall });
}

// Orphan sweep: settle bets left PENDING on an ALREADY-settled round. A
// bet that committed in the instant between the draw flip and the pending
// scan would otherwise be stranded unpaid, and settleRound's fast exit on
// a settled round would never revisit it. This reuses the exact guarded
// per-bet path, so a stranded bet is still credited exactly once, then it
// refreshes the round totals to include the just-paid winners.
export async function sweepStrandedBets(opts?: { limit?: number }): Promise<number> {
  const rounds = await db.wingoRound.findMany({
    where: {
      status: 'settled',
      result: { not: null },
      bets: { some: { status: 'PENDING' } },
    },
    orderBy: { drawsAt: 'asc' },
    take: Math.min(Math.max(opts?.limit ?? 100, 1), 500),
    select: { id: true, result: true, periodNumber: true },
  });

  let swept = 0;
  for (const r of rounds) {
    if (r.result === null) continue;
    const now = new Date();
    await drainPendingBets(r.id, r.result, r.periodNumber, now);
    // The round is already settled; only refresh its totals to fold in the
    // bets we just paid. No status flip needed.
    await finalizeRoundTotals(r.id, now, { settle: false });
    swept += 1;
  }
  return swept;
}

// ---------- Cron driver ----------

// Flip open -> closed for rounds whose betCloseAt has passed but that are
// not yet drawn. Purely cosmetic for state accuracy: bet acceptance is
// already time-guarded in placeBet, so a missed close never accepts a
// late bet.
export async function closeDueRounds(at: Date | number = Date.now()): Promise<number> {
  const now = new Date(typeof at === 'number' ? at : at.getTime());
  const upd = await db.wingoRound.updateMany({
    where: { status: 'open', betCloseAt: { lte: now } },
    data: { status: 'closed' },
  });
  return upd.count;
}

// Settle every round whose draw time has passed and that is not yet
// settled. Idempotent and safe to call every few seconds.
export async function settleDueRounds(opts?: { mode?: WingoMode; limit?: number; at?: Date | number }): Promise<SettleResult[]> {
  const now = new Date(opts?.at != null ? (typeof opts.at === 'number' ? opts.at : opts.at.getTime()) : Date.now());
  const due = await db.wingoRound.findMany({
    where: {
      status: { in: ['open', 'closed', 'drawn'] },
      drawsAt: { lte: now },
      ...(opts?.mode ? { mode: opts.mode } : {}),
    },
    orderBy: { drawsAt: 'asc' },
    take: Math.min(Math.max(opts?.limit ?? 200, 1), 500),
    select: { id: true },
  });
  const out: SettleResult[] = [];
  for (const r of due) {
    out.push(await settleRound(r.id));
  }
  return out;
}

export interface WingoTickSummary {
  ensuredModes: number;
  closed: number;
  settled: number;
  settledWon: number;
  // Rounds that had a bet stranded PENDING after settlement and were swept.
  swept: number;
}

// One-call cron driver: settle anything past its draw, sweep any bet left
// stranded PENDING on an already-settled round, close rounds past their
// bet-close, and ensure the current + next round exists for every mode.
// Idempotent; the VPS loopback crontab calls this every few seconds.
export async function wingoTick(at: Date | number = Date.now()): Promise<WingoTickSummary> {
  const settled = await settleDueRounds({ at });
  // Safety net: pay any bet that committed at the draw boundary and was
  // left PENDING on a round that has since flipped to settled.
  const swept = await sweepStrandedBets();
  const closed = await closeDueRounds(at);
  await Promise.all(WINGO_MODE_LIST.map((mode) => ensureRounds(mode, at)));
  return {
    ensuredModes: WINGO_MODE_LIST.length,
    closed,
    settled: settled.length,
    settledWon: settled.reduce((n, s) => n + s.betsWon, 0),
    swept,
  };
}
