// Built by Anointed Coder.
//
// Icon: a single shim that lets the app render the SAME icon set as the
// website (lucide) while every existing call site keeps passing the old
// Ionicons-style string names. Each Ionicons glyph name is mapped to the
// closest lucide-react-native component, so no call site has to change its
// icon name. Unknown names fall back to Circle so nothing can crash.
//
// Props:
//   name         string   the icon name (Ionicons-style, e.g. "wallet")
//   size         number   pixel size (default 20)
//   color        string   stroke color (lucide uses currentColor by default)
//   strokeWidth  number   stroke width (default 2, matches the web)

import {
  Activity,
  AlertCircle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  ArrowUp,
  ArrowUpCircle,
  Award,
  Banknote,
  BarChart3,
  Bell,
  BellOff,
  Box,
  Building2,
  Calendar,
  Camera,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleDot,
  Clock,
  CloudOff,
  Copy,
  CreditCard,
  Dice5,
  Disc,
  Eye,
  EyeOff,
  FileText,
  Flame,
  Gamepad2,
  Gem,
  Gift,
  Globe,
  Grid3x3,
  Hand,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  Hourglass,
  Info,
  KeyRound,
  Languages,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Medal,
  Megaphone,
  Menu,
  MessageCircle,
  Minus,
  Palette,
  Pause,
  PauseCircle,
  Pencil,
  Phone,
  Play,
  Plus,
  PlusCircle,
  QrCode,
  ReceiptText,
  RefreshCw,
  Rocket,
  RotateCw,
  Search,
  Send,
  Share2,
  ShieldCheck,
  Shuffle,
  Skull,
  Smartphone,
  Sparkles,
  Star,
  Tag,
  Tags,
  Ticket,
  Trash2,
  TrendingUp,
  Trophy,
  UploadCloud,
  User,
  UserPlus,
  Users,
  Wallet,
  Wand2,
  Wrench,
  X,
  XCircle,
  Zap,
  Goal,
  Dribbble,
  Target,
  PieChart,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react-native';

export interface IconProps {
  name: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
  style?: LucideProps['style'];
}

// Ionicons glyph name  ->  lucide component.
// Both the "-outline" and filled Ionicons variants point at the same lucide
// icon (lucide has one line-weight per glyph, tuned by strokeWidth).
const NAME_MAP: Record<string, LucideIcon> = {
  // ---- add / remove ----
  add: Plus,
  'add-circle': PlusCircle,
  'add-circle-outline': PlusCircle,
  remove: Minus,
  'remove-outline': Minus,

  // ---- arrows / chevrons ----
  'arrow-back': ArrowLeft,
  'arrow-back-outline': ArrowLeft,
  'arrow-forward': ArrowRight,
  'arrow-forward-outline': ArrowRight,
  'arrow-down': ArrowDown,
  'arrow-up': ArrowUp,
  'arrow-up-circle': ArrowUpCircle,
  'arrow-up-circle-outline': ArrowUpCircle,
  'swap-horizontal': ArrowRightLeft,
  'chevron-back': ChevronLeft,
  'chevron-forward': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,

  // ---- status / alerts ----
  'alert-circle': AlertCircle,
  'alert-circle-outline': AlertCircle,
  checkmark: Check,
  'checkmark-outline': Check,
  'checkmark-circle': CheckCircle2,
  'checkmark-circle-outline': CheckCircle2,
  'checkmark-done': CheckCheck,
  'checkmark-done-outline': CheckCheck,
  close: X,
  'close-outline': X,
  'close-circle': XCircle,
  'close-circle-outline': XCircle,
  'information-circle': Info,
  'information-circle-outline': Info,
  'shield-checkmark': ShieldCheck,
  'shield-checkmark-outline': ShieldCheck,

  // ---- money / wallet ----
  wallet: Wallet,
  'wallet-outline': Wallet,
  cash: Banknote,
  'cash-outline': Banknote,
  card: CreditCard,
  'card-outline': CreditCard,
  'receipt-outline': ReceiptText,
  receipt: ReceiptText,
  'pricetag-outline': Tag,
  pricetag: Tag,
  'pricetags-outline': Tags,
  pricetags: Tags,

  // ---- brand / rewards ----
  diamond: Gem,
  'diamond-outline': Gem,
  trophy: Trophy,
  'trophy-outline': Trophy,
  medal: Medal,
  'medal-outline': Medal,
  podium: Medal,
  'podium-outline': Medal,
  ribbon: Award,
  'ribbon-outline': Award,
  gift: Gift,
  'gift-outline': Gift,
  ticket: Ticket,
  'ticket-outline': Ticket,
  star: Star,
  'star-outline': Star,
  heart: Heart,
  'heart-outline': Heart,
  sparkles: Sparkles,
  'sparkles-outline': Sparkles,
  flame: Flame,
  'flame-outline': Flame,
  rocket: Rocket,
  'rocket-outline': Rocket,

  // ---- games ----
  'game-controller': Gamepad2,
  'game-controller-outline': Gamepad2,
  dice: Dice5,
  'dice-outline': Dice5,

  // ---- sport chips + charts (distinct glyphs so the chips do not all look alike) ----
  football: Goal,
  basketball: Dribbble,
  baseball: Target,
  tennisball: CircleDot,
  'pie-chart': PieChart,
  'pie-chart-outline': PieChart,
  disc: Disc,
  'disc-outline': Disc,
  ellipse: Circle,
  'ellipse-outline': Circle,
  skull: Skull,
  'skull-outline': Skull,
  shuffle: Shuffle,
  flash: Zap,
  'flash-outline': Zap,

  // ---- people / account ----
  person: User,
  'person-outline': User,
  'person-circle': User,
  'person-circle-outline': User,
  people: Users,
  'people-outline': Users,
  'log-in-outline': LogIn,
  'log-in': LogIn,
  'log-out-outline': LogOut,
  'log-out': LogOut,
  'lock-closed': Lock,
  'lock-closed-outline': Lock,
  'key-outline': KeyRound,
  key: KeyRound,
  'create-outline': Pencil,
  create: Pencil,
  'hand-left': Hand,
  'hand-left-outline': Hand,
  'hand-right': Hand,
  'hand-right-outline': Hand,
  'person-add': UserPlus,
  'person-add-outline': UserPlus,
  'radio-button-on': CircleDot,
  'radio-button-off': Circle,

  // ---- chrome / nav ----
  menu: Menu,
  'menu-outline': Menu,
  search: Search,
  'search-outline': Search,
  notifications: Bell,
  'notifications-outline': Bell,
  'notifications-off-outline': BellOff,
  'notifications-off': BellOff,
  home: Home,
  'home-outline': Home,
  grid: Grid3x3,
  'grid-outline': Grid3x3,
  'keypad-outline': Grid3x3,
  keypad: Grid3x3,

  // ---- comms / support ----
  mail: Mail,
  'mail-outline': Mail,
  'call-outline': Phone,
  call: Phone,
  'phone-portrait': Smartphone,
  'phone-portrait-outline': Smartphone,
  send: Send,
  'send-outline': Send,
  'paper-plane-outline': Send,
  'paper-plane': Send,
  'chatbox-ellipses-outline': MessageCircle,
  'chatbox-ellipses': MessageCircle,
  'chatbubbles-outline': MessageCircle,
  chatbubbles: MessageCircle,
  'logo-whatsapp': MessageCircle,
  'headset-outline': Headphones,
  headset: Headphones,
  'help-circle-outline': HelpCircle,
  help: HelpCircle,
  'help-outline': HelpCircle,
  'megaphone-outline': Megaphone,
  megaphone: Megaphone,

  // ---- time ----
  time: Clock,
  'time-outline': Clock,
  hourglass: Hourglass,
  'hourglass-outline': Hourglass,
  calendar: Calendar,
  'calendar-outline': Calendar,

  // ---- media controls ----
  play: Play,
  'play-outline': Play,
  pause: Pause,
  'pause-outline': Pause,
  'pause-circle': PauseCircle,
  'pause-circle-outline': PauseCircle,

  // ---- utility ----
  refresh: RefreshCw,
  'refresh-outline': RefreshCw,
  sync: RotateCw,
  'sync-outline': RotateCw,
  copy: Copy,
  'copy-outline': Copy,
  'share-social-outline': Share2,
  'share-social': Share2,
  'trending-up': TrendingUp,
  'bar-chart': BarChart3,
  'bar-chart-outline': BarChart3,
  'stats-chart': BarChart3,
  'stats-chart-outline': BarChart3,
  cube: Box,
  'cube-outline': Box,
  pulse: Activity,
  trash: Trash2,
  'trash-outline': Trash2,
  'color-wand-outline': Wand2,
  'color-palette': Palette,
  'color-palette-outline': Palette,
  eye: Eye,
  'eye-outline': Eye,
  'eye-off': EyeOff,
  'eye-off-outline': EyeOff,
  globe: Globe,
  'globe-outline': Globe,
  language: Languages,
  'language-outline': Languages,
  languages: Languages,
  business: Building2,
  'business-outline': Building2,
  'document-text-outline': FileText,
  'document-text': FileText,
  'qr-code-outline': QrCode,
  'qr-code': QrCode,
  'cloud-offline': CloudOff,
  'cloud-offline-outline': CloudOff,
  'cloud-upload-outline': UploadCloud,
  'cloud-upload': UploadCloud,
  construct: Wrench,
  'construct-outline': Wrench,
  camera: Camera,
  'camera-outline': Camera,
};

const FALLBACK: LucideIcon = Circle;

export function Icon({ name, size = 20, color, strokeWidth = 2, style }: IconProps) {
  const Glyph = NAME_MAP[name] ?? FALLBACK;
  return <Glyph size={size} color={color} strokeWidth={strokeWidth} style={style} />;
}
