// Built by Anointed Coder.
//
// /lotto - public Lotto landing.
//
// Babu88-style flat layout (per client direction): Winner of the Day
// header, 1st/2nd/3rd prize cards, Special grid, Consolation grid,
// next-draw countdown, Earn Tickets CTA, per-user winnings + ticket
// stats, brand ambassadors, sponsorships, and the FAQ accordion at
// the bottom. The premium Cinzel + ball-tumbler + certificate
// components were retired in favour of the conventional layout the
// client signed off on.

'use client';

import { useCallback, useEffect, useState } from 'react';
import { BackBar } from '@/components/site/BackBar';
import { useLang } from '@/lib/i18n/context';
import { ChevronDown, Sparkles } from 'lucide-react';
import { cn } from '@/lib/utils/cn';
import { triggerWalletRefresh } from '@/components/site/WalletStrip';
import { LottoBabuLayout, type AmbassadorRow } from '@/components/site/LottoBabuLayout';

interface LiveDraw {
  id: string;
  name: string;
  drawsAt: string | null;
  schedule: string | null;
}

interface ResultRow {
  id: string;
  drawId: string;
  drawName: string;
  drawsAt: string | null;
  winningNumber: string;
  publishedAt: string;
  totalWinners: number;
  totalPaid: number;
  ticketBaseValue: number;
  prize1xMult: number;
  extraNumbers?: {
    second?: string | null;
    third?: string | null;
    specials?: string[];
    consolations?: string[];
  } | null;
}

interface MeResponse {
  summary: { ticketCount: number; wonCount: number; winningCount: number };
  lottoBalance: number;
  tickets: Array<{ id: string; status: string }>;
  winnings: Array<{
    id: string;
    amount: number;
    status: string;
    drawId: string | null;
  }>;
}

const FAQ_ITEMS = [
  {
    qEn: '1. What is Pasha 9 4D Lottery?',
    qBn: '১. পাশা ৯ 4D লটারি কী?',
    aEn: 'A daily 4-digit lottery drawn every evening at 7:30 PM. Each ticket holds a random 4-digit number; if the draw matches, the ticket wins.',
    aBn: 'প্রতিদিন সন্ধ্যা ৭:৩০ টায় ড্র হয় এমন একটি ৪-অঙ্কের লটারি। প্রতিটি টিকেটে একটি র‍্যান্ডম ৪-অঙ্কের নম্বর থাকে; ড্রয়ের সাথে মিললে টিকেট জিতে যায়।',
  },
  {
    qEn: '2. How do I enter the lottery?',
    qBn: '২. লটারিতে কীভাবে অংশ নেব?',
    aEn: 'Tickets are generated automatically when an admin approves your deposit. Every BDT 1,200 of approved deposits earns you 2 tickets.',
    aBn: 'অ্যাডমিন ডিপোজিট অনুমোদন করলেই টিকেট স্বয়ংক্রিয়ভাবে তৈরি হয়। অনুমোদিত মোট প্রতি ১,২০০ টাকায় ২টি টিকেট পাবেন।',
  },
  {
    qEn: '3. What does a lottery ticket look like?',
    qBn: '৩. লটারির টিকেট দেখতে কেমন?',
    aEn: 'Each ticket is a randomly generated 4-digit number. Example: 1284, 5930, 7741. All numbers are automatically generated by the Pasha 9 system.',
    aBn: 'প্রতিটি টিকেট একটি র‍্যান্ডম জেনারেটেড ৪-অঙ্কের নম্বর। উদাহরণ: 1284, 5930, 7741। সমস্ত নম্বর পাশা ৯ সিস্টেম দ্বারা স্বয়ংক্রিয়ভাবে তৈরি হয়।',
  },
  {
    qEn: '4. What are iBox tickets?',
    qBn: '৪. iBox টিকেট কী?',
    aEn: 'If your ticket matches the winning number in any order, it wins under iBox.',
    aBn: 'যদি আপনার টিকেট জয়ী নম্বরের সাথে যেকোনো ক্রমে মিলে যায়, এটি iBox এর অধীনে জিতে যাবে।',
  },
  {
    qEn: '5. How does iBox affect my winnings?',
    qBn: '৫. iBox কীভাবে আপনার জয়কে প্রভাবিত করে?',
    aEn: 'For numbers with all-different digits like 1234, the prize is split across 24 unique permutations. For identical digits like 1111, only one permutation exists, so the full prize is paid.',
    aBn: '১২৩৪ এর মতো ভিন্ন অঙ্কে পুরস্কার ২৪টি ইউনিক পারমুটেশনে ভাগ হয়। ১১১১ এর মতো এক অঙ্কে শুধু একটিই পারমুটেশন থাকে, তাই পুরো পুরস্কার দেওয়া হয়।',
  },
  {
    qEn: '6. What is the prize structure?',
    qBn: '৬. পুরস্কার কাঠামো কী?',
    aEn: 'Each ticket has a value of ৳20. Prizes are multipliers of that value: 1st Prize 2,000x, 2nd Prize 800x, 3rd Prize 300x, Special (10 winners) 150x, Consolation (10 winners) 30x. Example: 1st Prize = ৳20 × 2,000 = ৳40,000.',
    aBn: 'প্রতিটি টিকেটের মূল্য ২০ টাকা। পুরস্কার গুণিতক হিসেবে গণনা হয়: ১ম ২০০০x, ২য় ৮০০x, ৩য় ৩০০x, বিশেষ (১০ জন) ১৫০x, সান্ত্বনা (১০ জন) ৩০x। উদাহরণ: ১ম = ২০ × ২০০০ = ৪০,০০০ টাকা।',
  },
  {
    qEn: '7. When is the lottery draw?',
    qBn: '৭. লটারির ড্র কখন হয়?',
    aEn: 'Every day at 7:30 PM Bangladesh time. The winning number is published as soon as the admin settles the draw.',
    aBn: 'প্রতিদিন সন্ধ্যা ৭:৩০ টা (বাংলাদেশ সময়)। অ্যাডমিন ড্র সেটল করার সাথে সাথে জয়ী নম্বর প্রকাশিত হয়।',
  },
  {
    qEn: '8. How do I receive my winnings?',
    qBn: '৮. আমি কীভাবে আমার জয় পাব?',
    aEn: 'Winnings credit to your Lotto Balance the moment the admin publishes the result. You can then claim them and transfer to your main wallet.',
    aBn: 'অ্যাডমিন ফলাফল প্রকাশ করার সাথে সাথে জয়ী অর্থ স্বয়ংক্রিয়ভাবে আপনার লটো ব্যালেন্সে যোগ হয়। দাবি করে মেইন ওয়ালেটে নিতে পারবেন।',
  },
  {
    qEn: '9. How can I get more tickets?',
    qBn: '৯. আমি আরও টিকেট কীভাবে পাব?',
    aEn: 'More deposits, more tickets. Every accumulated BDT 1,200 of approved deposits generates 2 additional tickets.',
    aBn: 'বেশি ডিপোজিট মানে বেশি টিকেট। অনুমোদিত প্রতি ১,২০০ টাকায় অতিরিক্ত ২টি টিকেট পাবেন।',
  },
  {
    qEn: '10. Terms and Conditions',
    qBn: '১০. শর্তাবলী',
    aEn: 'Only approved deposits qualify for ticket generation. Refunded or reversed deposits do not earn tickets. Pasha 9 reserves the right to pause or amend the lottery at any time. Settlement is final once the admin publishes the result.',
    aBn: 'শুধুমাত্র অনুমোদিত ডিপোজিট টিকেট তৈরির জন্য যোগ্য। ফেরত বা রিভার্স করা ডিপোজিটে টিকেট তৈরি হয় না। পাশা ৯ যেকোনো সময় লটারি স্থগিত বা সংশোধন করার অধিকার রাখে। অ্যাডমিন ফলাফল প্রকাশের পর সেটলমেন্ট চূড়ান্ত।',
  },
];

export default function LottoPage() {
  const { lang } = useLang();
  const [draws, setDraws] = useState<LiveDraw[]>([]);
  const [latest, setLatest] = useState<ResultRow | null>(null);
  const [previousResult, setPreviousResult] = useState<ResultRow | null>(null);
  const [me, setMe] = useState<MeResponse | null>(null);
  const [ambassadors, setAmbassadors] = useState<AmbassadorRow[]>([]);
  const [sponsors, setSponsors] = useState<AmbassadorRow[]>([]);
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const [claimBusy, setClaimBusy] = useState(false);

  const loadMe = useCallback(async () => {
    try {
      const r = await fetch('/api/lotto/me', { cache: 'no-store', credentials: 'include' });
      if (!r.ok) { setMe(null); return; }
      const j = await r.json().catch(() => null);
      if (j && !j.code) setMe(j as MeResponse);
    } catch { /* swallow */ }
  }, []);

  useEffect(() => {
    let alive = true;
    fetch('/api/content/lotto')
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => {
        if (alive) setDraws(Array.isArray(data?.draws) ? (data.draws as LiveDraw[]) : []);
      })
      .catch(() => {});

    // Pull the latest two published results: the newest powers the
    // Winner of the Day block, the second-newest is what the
    // "Last Draw Winning Tickets" stat counts against.
    fetch('/api/content/lotto/results?take=2')
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => {
        if (!alive) return;
        const arr = Array.isArray(data?.results) ? (data.results as ResultRow[]) : [];
        setLatest(arr[0] ?? null);
        setPreviousResult(arr[1] ?? null);
      })
      .catch(() => {});

    loadMe();

    fetch('/api/content/about-display')
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => {
        if (!alive) return;
        setAmbassadors(Array.isArray(data?.ambassadors) ? (data.ambassadors as AmbassadorRow[]) : []);
        setSponsors(Array.isArray(data?.sponsors) ? (data.sponsors as AmbassadorRow[]) : []);
      })
      .catch(() => {});

    return () => { alive = false; };
  }, [loadMe]);

  // Resolve next draw time. Prefer the live draws endpoint first;
  // fall back to derived value from the last result if needed.
  const nextDrawAt = draws[0]?.drawsAt ?? null;

  // Build the Babu layout's MeBlock from whatever the /api/lotto/me
  // response gave us. When the visitor is not signed in we hand the
  // layout null and it renders the sign-in hint.
  const meBlock = me
    ? (() => {
        const activeTickets = me.tickets.filter((t) => t.status === 'issued').length;
        const lastDrawWinningTickets = previousResult
          ? me.winnings.filter((w) => w.drawId === previousResult.drawId).length
          : 0;
        const pendingClaim = me.winnings
          .filter((w) => w.status === 'pending_credit')
          .reduce((acc, w) => acc + Number(w.amount), 0);
        const lifetimeWinnings = me.winnings
          .filter((w) => w.status !== 'cancelled')
          .reduce((acc, w) => acc + Number(w.amount), 0);
        return {
          activeTickets,
          lastDrawWinningTickets,
          pendingClaimTotal: pendingClaim,
          lifetimeWinnings,
          hasClaimable: pendingClaim > 0,
        };
      })()
    : null;

  // Click handler for the Claim button: claims every pending winning
  // in sequence. The /api/lotto/winnings/:id/claim endpoint is
  // transactional and idempotent so this loop is safe even if the
  // user mashes the button mid-flight.
  const onClaim = async () => {
    if (!me) return;
    setClaimBusy(true);
    try {
      const pending = me.winnings.filter((w) => w.status === 'pending_credit');
      for (const w of pending) {
        await fetch(`/api/lotto/winnings/${w.id}/claim`, {
          method: 'POST',
          credentials: 'include',
        }).catch(() => null);
      }
      triggerWalletRefresh();
      await loadMe();
    } finally {
      setClaimBusy(false);
    }
  };

  // Map the result row into the layout's expected `latest` shape.
  const layoutLatest = latest
    ? {
        drawName: latest.drawName,
        publishedAt: latest.publishedAt,
        winningNumber: latest.winningNumber,
        second: latest.extraNumbers?.second ?? null,
        third: latest.extraNumbers?.third ?? null,
        specials: Array.isArray(latest.extraNumbers?.specials) ? (latest.extraNumbers!.specials as string[]) : [],
        consolations: Array.isArray(latest.extraNumbers?.consolations) ? (latest.extraNumbers!.consolations as string[]) : [],
      }
    : null;

  return (
    <div className="space-y-5">
      <BackBar title={lang === 'bn' ? 'লটো' : 'Lotto'} />

      <LottoBabuLayout
        latest={layoutLatest}
        nextDrawAt={nextDrawAt}
        me={meBlock}
        ambassadors={ambassadors}
        sponsors={sponsors}
        onClaim={onClaim}
        claimBusy={claimBusy}
      />

      {/* Lottery Rules and FAQ (collapsible accordion, matches the
          reference layout at the bottom of the page). */}
      <section>
        <div className="mb-3 flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-brand-yellow-600" />
          <h3 className="text-base font-extrabold text-brand-ink md:text-lg">
            {lang === 'bn' ? 'লটারি নিয়মাবলী এবং প্রশ্ন' : 'Lottery Rules & FAQ'}
          </h3>
        </div>
        <div className="space-y-2">
          {FAQ_ITEMS.map((item, i) => {
            const isOpen = openFaq === i;
            return (
              <div key={i} className="overflow-hidden rounded-xl border border-brand-divider bg-brand-paper">
                <button
                  type="button"
                  onClick={() => setOpenFaq(isOpen ? null : i)}
                  aria-expanded={isOpen}
                  className="flex w-full items-center justify-between gap-3 px-4 py-3.5 text-left transition hover:bg-brand-surface"
                >
                  <span className="text-sm font-bold text-brand-ink md:text-base">
                    {lang === 'bn' ? item.qBn : item.qEn}
                  </span>
                  <ChevronDown
                    className={cn(
                      'h-4 w-4 shrink-0 text-brand-inkMute transition-transform',
                      isOpen && 'rotate-180 text-brand-ink',
                    )}
                  />
                </button>
                {isOpen ? (
                  <div className="border-t border-brand-divider bg-brand-surface px-4 py-3.5 text-sm leading-relaxed text-brand-inkSoft whitespace-pre-line">
                    {lang === 'bn' ? item.aBn : item.aEn}
                  </div>
                ) : null}
              </div>
            );
          })}
        </div>
      </section>
    </div>
  );
}
