export const ROUTES = {
  home: '/',
  games: '/games',
  category: (slug: string) => `/games/${slug}`,
  dice: '/games/dice',
  mines: '/games/mines',
  keno: '/games/keno',
  roulette: '/games/roulette',
  nativeSlots: '/games/slots',
  crash: '/games/crash',
  sports: '/sports',
  liveCasino: '/live-casino',
  slots: '/slots',
  fishing: '/fishing',
  lottery: '/lottery',
  promotions: '/promotions',
  referral: '/referral',
  wallet: '/wallet',
  deposit: '/deposit',
  withdraw: '/withdraw',
  transactions: '/transactions',
  profile: '/profile',
  support: '/support',
  terms: '/terms',
  responsible: '/responsible-gaming',
  dashboard: {
    home: '/dashboard',
    wallet: '/dashboard/wallet',
    deposit: '/dashboard/deposit',
    withdraw: '/dashboard/withdraw',
    bonus: '/dashboard/bonus',
    referral: '/dashboard/referral',
    transactions: '/dashboard/transactions',
    profile: '/dashboard/profile',
    security: '/dashboard/security',
  },
  admin: {
    login: '/admin/login',
    home: '/admin',
    users: '/admin/users',
    affiliate: '/admin/affiliate',
    affiliateTiers: '/admin/affiliate/tiers',
    balance: '/admin/balance',
    deposits: '/admin/deposits',
    withdrawals: '/admin/withdrawals',
    transactions: '/admin/transactions',
    referrals: '/admin/referrals',
    bonuses: '/admin/bonuses',
    banners: '/admin/banners',
    popups: '/admin/popups',
    categories: '/admin/categories',
    providers: '/admin/providers',
    homepage: '/admin/homepage',
    homepageSections: '/admin/homepage-sections',
    promoText: '/admin/promo-text',
    support: '/admin/support',
    settings: '/admin/settings',
    activity: '/admin/activity',
    handover: '/admin/handover',
    website: '/admin/website',
    staff: '/admin/staff',
    reports: '/admin/reports',
    security: '/admin/security',
    marketing: '/admin/marketing',
    payments: '/admin/payments',
    paymentsReconciliation: '/admin/payments/reconciliation',
    payouts: '/admin/payouts',
    paymentMethods: '/admin/payment-methods',
    withdrawalLimits: '/admin/withdrawal-limits',
    recovery: '/admin/recovery',
    notifications: '/admin/notifications',
    integrations: '/admin/integrations',
    nativeGames: '/admin/native-games',
    depositPrompt: '/admin/deposit-prompt',
    whatsapp: '/admin/whatsapp',
    // M3: tracking lives as a tab inside /admin/notifications. We
    // surface it as its own sidebar entry pointing at the deep link
    // so operators do not have to know it is a tab.
    tracking: '/admin/notifications?tab=tracking',
  },
} as const;
